In [1]:
'''
This script reads a .csv file and generates the Compute Area Under the
Receiver Operating Characteristic Curve (ROC AUC) results from prediction scores.
'''
from classfunc import *

In [2]:
# Loading and splitting the data

data_dir = 'sample_diabetes_mellitus_data.csv'
data = load_and_split(data_dir)

In [3]:
# Extracting the two dataframes created from load_and_split

df_Train = data.Train
df_Test = data.Test

In [4]:
# Removing NaN rows in predefined columns

nancols = ['age','gender','ethnicity']

train_clean = remove_nan(df_Train,nancols).cleaned_df
test_clean = remove_nan(df_Test,nancols).cleaned_df

In [5]:
# Filling NaN with the mean value of predefined columns

meancols = ['height','weight']

train_fill = fill_nan(train_clean,meancols).df
test_fill = fill_nan(test_clean,meancols).df

/home/djtom/bse/.venv/lib/python3.8/site-packages/classfunc/meanfill.py:25: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  self.df.loc[:,cols] = self.df.loc[:,cols].fillna(self.df.mean())
/home/djtom/bse/.venv/lib/python3.8/site-packages/classfunc/meanfill.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.df.loc[:,cols] = self.df.loc[:,cols].fillna(self.df.mean())
/home/djtom/bse/.venv/lib/python3.8/site-packages/classfunc/meanfill.py:25: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  self.df.loc[:,cols] = self.df.loc[:,cols].fillna(self.df.mean())
/home/djtom/bse/.venv/lib/python3.8/site-packages/classfunc/meanfill.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.df.loc[:,cols] = self.df.loc[:,cols].fillna(self.df.mean())

In [6]:
# Checking to see that NaN were replaced

train_fill[train_fill['height'].isna()]

Empty DataFrame
Columns: [encounter_id, hospital_id, age, bmi, elective_surgery, ethnicity, gender, height, hospital_admit_source, icu_admit_source, icu_id, icu_stay_type, icu_type, pre_icu_los_days, readmission_status, weight, albumin_apache, apache_2_diagnosis, apache_3j_diagnosis, apache_post_operative, arf_apache, bilirubin_apache, bun_apache, creatinine_apache, fio2_apache, gcs_eyes_apache, gcs_motor_apache, gcs_unable_apache, gcs_verbal_apache, glucose_apache, heart_rate_apache, hematocrit_apache, intubated_apache, map_apache, paco2_apache, paco2_for_ph_apache, pao2_apache, ph_apache, resprate_apache, sodium_apache, temp_apache, urineoutput_apache, ventilated_apache, wbc_apache, aids, cirrhosis, hepatic_failure, immunosuppression, leukemia, lymphoma, solid_tumor_with_metastasis, diabetes_mellitus]
Index: []

[0 rows x 52 columns]

In [7]:
# Creating features: taking the log and one-hot encoding categorical variables

train_feats = log_transform(train_fill,meancols)
train_feats.apply_transform()
train_feats = train_feats.df
train_feats = one_hot_encoding(train_feats).df

test_feats = log_transform(test_fill,meancols)
test_feats.apply_transform()
test_feats = test_feats.df
test_feats = one_hot_encoding(test_feats).df

/home/djtom/bse/.venv/lib/python3.8/site-packages/classfunc/transf.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.df.loc[:,self.cols]=self.df.loc[:,self.cols].apply(lambda x: np.log(x))
/home/djtom/bse/.venv/lib/python3.8/site-packages/classfunc/transf.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.df.loc[:,self.cols]=self.df.loc[:,self.cols].apply(lambda x: np.log(x))

In [8]:
# Checking that the data is in the format we want
train_feats.head(10)

,encounter_id,hospital_id,age,bmi,elective_surgery,height,icu_id,pre_icu_los_days,readmission_status,weight,...,icu_admit_source_Other ICU,icu_stay_type_admit,icu_stay_type_readmit,icu_stay_type_transfer,icu_type_CCU-CTICU,icu_type_CTICU,icu_type_MICU,icu_type_Med-Surg ICU,icu_type_Neuro ICU,icu_type_SICU
3194,220344,118,87.0,18.820156,0,5.106551,97,0.004861,0,3.937691,...,0,1,0,0,0,0,1,0,0,0
1507,226441,118,32.0,20.859034,0,5.166499,97,0.004167,0,4.160444,...,0,1,0,0,0,0,1,0,0,0
3438,162338,81,44.0,53.515625,1,5.075174,90,0.006944,0,4.919981,...,0,1,0,0,0,0,0,1,0,0
9707,249592,140,74.0,26.615539,0,5.136974,126,0.000000,0,4.345103,...,0,1,0,0,0,0,0,1,0,0
9547,184294,140,86.0,26.065657,0,5.166499,126,0.005556,0,4.383276,...,0,1,0,0,0,0,0,1,0,0
799,164780,118,19.0,21.465821,0,5.249652,99,0.003472,0,4.355426,...,0,1,0,0,0,0,0,1,0,0
1716,264550,118,67.0,33.104399,1,5.083266,93,1.113194,0,4.455858,...,0,1,0,0,0,0,0,1,0,0
7894,231723,151,72.0,NaN,1,5.136974,109,1.154167,0,4.467089,...,0,1,0,0,0,0,0,1,0,0
5843,182384,63,41.0,22.748735,0,5.208940,108,0.000000,0,4.332048,...,0,1,0,0,0,0,0,1,0,0
6529,213509,118,87.0,18.946838,0,5.059425,89,0.001389,0,3.850148,...,0,1,0,0,0,0,0,0,1,0

In [9]:
# Training the model on the train set
X_cols = [col for col in train_feats if col.startswith('ethnicity') or col.startswith('gender') or 
            col.startswith('hospital') or col.startswith('icu') or col.startswith('height') or 
          col.startswith('weight')]

X_cols.remove('hospital_admit_source_Chest Pain Center') # removing this dummy that does not exist in the test set

target = ['diabetes_mellitus']
mod = model(train_feats, rf, X_cols, target, hyperparams)

/home/djtom/bse/.venv/lib/python3.8/site-packages/classfunc/model.py:30: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.model = self.model.fit(X_train, y_train)

In [10]:
# Predicting diabetes status

test_pred = mod.predict(test_feats)

test_feats['test_pred'] = test_pred.tolist()

In [11]:
# Calculating ROC AUC from prediction scores
mod.get_roc_auc_score()

SCORING...

0.6664315897588483